spring.application.name=marketplace
spring.mvc.problemdetails.enabled=true

# Feature Flags
feature.cosmoCats.enabled=true
feature.kittyProducts.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace?currentSchema=public
spring.datasource.username=admin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public