openapi: 3.0.3
info:
  title: Cosmo Cats Marketplace API
  version: 1.0.0
paths:
  /api/v1/products:
    get:
      summary: Retrieve all products
      responses:
        '200':
          description: Successfully returned a list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Validation failed (e.g. negative price)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    put:
      summary: Update a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      summary: Delete a product by ID
      responses:
        '204':
          description: Product deleted successfully
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          minLength: 1
          example: "Toys"
        description:
          type: string
          minLength: 1
          example: "Fun things for space cats"
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          minLength: 1
          example: "Big Balls"
        category:
          $ref: '#/components/schemas/Category'
        description:
          type: string
          minLength: 1
          example: "Nice product"
        price:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
          example: 6.7
        quantity:
          type: integer
          format: int64
          minimum: 0
          example: 1
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "Validation failed..."
        path:
          type: string
          example: "/api/products"